@server=http://localhost:4001/odata/v4/developer



### Tasks
# @name Tasks_GET
GET {{server}}/Tasks


### Get Metadata
# @name GetMetadata
GET {{server}}/$metadata

### Get Task Logs
# @name GetTaskLogs
GET {{server}}/TaskLogs



### Submit Task
# @name SubmitTask
POST {{server}}/submitTask
Content-Type: application/json

{
  "projectName": "MyProject",
  "taskDescription": "Implement feature X",
  "filePath": "/path/to/file"
}

